language: bash
sudo: required
services:
  - podman

env:
  matrix:
    - PHP_VERSION=5.6
    - PHP_VERSION=7.0
    - PHP_VERSION=7.1
    - PHP_VERSION=7.2
    - PHP_VERSION=7.3
    - PHP_VERSION=7.4
    - PHP_VERSION=8.0
    - PHP_VERSION=8.1
    - PHP_VERSION=8.2
    - PHP_VERSION=8.3
    - PHP_VERSION=8.4

# Installing a newer Docker version
before_install:
  - sudo apt-get update
  - sudo apt-get -y install podman
  - docker version

script: ./travis-build.sh
